const EXACT_EN_MAP = {
  "Qo'shish": 'Add',
  "O'chirish": 'Delete',
  "Bekor qilish": 'Cancel',
  'Saqlash': 'Save',
  'Yopish': 'Close',
  'Yangilash': 'Refresh',
  'Oldingi': 'Previous',
  'Keyingi': 'Next',
  'Qidirish': 'Search',
  'Qidirish...': 'Search...',
  'Batafsil': 'Details',
  Amal: 'Action',
  Amallar: 'Actions',
  "Fanlar boshqaruvi": 'Subject management',
  "Sinflar boshqaruvi": 'Classroom management',
  "Teacherlar ro'yxati": 'Teachers list',
  "Studentlar ro'yxati": 'Students list',
  "Barcha sinflar": 'All classrooms',
  "Hujjatlar mavjud emas": 'No documents available',
  "To'lov ma'lumoti topilmadi": 'No payment data found',
  "To'lovlar ro'yxati": 'Payment list',
  "To'lov preview": 'Payment preview',
  "To'lovni saqlash": 'Save payment',
  "Imtiyoz berish": 'Give discount',
  "Imtiyozni saqlash": 'Save discount',
  "Berilgan imtiyozlar": 'Applied discounts',
  "Imtiyozlar yo'q": 'No discounts',
  "To'liq ozod": 'Full exemption',
  "Yillik avtomat o'tkazish": 'Annual auto promotion',
  "Yillik sinf yangilash (Sentyabr)": 'Annual class promotion (September)',
  "Tasdiqlab avtomat o'tkazish": 'Confirm and run auto promotion',
  "Preview yangilash": 'Refresh preview',
  "Bo'sh slot": 'Empty slot',
  "Haftalik jadval": 'Weekly schedule',
  "Dars qo'shish": 'Add lesson',
  "Vaqt oralig'i qo'shish": 'Add time slot',
  "Vaqtlar ro'yxati": 'Time slots list',
  "Fan ranglari": 'Subject colors',
  "Haftalik jadval ko'rinishi": 'Weekly schedule view',
  "Dars jadvali boshqaruvi": 'Schedule management',
  "Davomat bo'limi": 'Attendance section',
  "Davomat hisobotlari": 'Attendance reports',
  "Hisobotni yangilash": 'Refresh report',
  "Excel export": 'Excel export',
  "PDF export": 'PDF export',
  "Menejer faqat qarzdor o'quvchilar bilan ishlaydi va ota-ona bilan aloqa izohini yozadi.":
    'Manager works only with debtors and writes parent communication notes.',
  "Qarzdorlar ro'yxati": 'Debtors list',
  "Ota-ona bilan aloqa izohlari": 'Parent communication notes',
  "To'lov tranzaksiyalari": 'Payment transactions',
  "To'lovlar tarixi": 'Payment history',
  "Yangi izoh qo'shish": 'Add new note',
  "Izoh yo'q": 'No notes',
  "Hali izoh kiritilmagan.": 'No notes added yet.',
  "O'quvchi tanlanmagan.": 'No student selected.',
  "Student tanlanmagan": 'No student selected',
  "Qarzdor o'quvchi topilmadi.": 'No debtor student found.',
  "Sinf o'quvchilari": 'Classroom students',
  'Profil': 'Profile',
  'Hujjatlar': 'Documents',
  'Faoliyat': 'Activity',
  "Profil ma'lumotlari": 'Profile information',
  "Teacher profili": 'Teacher profile',
  "Student profili": 'Student profile',
  "Ro'yxatga qaytish": 'Back to list',
  'Avatar': 'Avatar',
  'Avatar yo`q': 'No avatar',
  'Avatar yuklash': 'Upload avatar',
  "Avatar o`chirish": 'Delete avatar',
  "Parolni yangilash": 'Reset password',
  "Hujjatni yangilash": 'Update document',
  "Hujjat qo`shish": 'Add document',
  Sarlavha: 'Title',
  'Download': 'Download',
  'Edit': 'Edit',
  'Delete': 'Delete',
  "Tushunarli": 'Understood',
  "Jadval xatosi": 'Schedule error',
  "Barcha sinflar davomat tarixi": 'Attendance history for all classrooms',
  "Tanlangan period bo'yicha tarix topilmadi": 'No history found for selected period',
  "Tanlangan davrda yopiladigan qarz oy topilmadi.": 'No debt months can be closed for selected period.',
  "Ixtiyoriy to'lovda summa majburiy.": 'Amount is required for custom payment.',
  "Yuboriladigan summa kutilgan summa bilan bir xil bo'lishi kerak.":
    'Submitted amount must match expected amount.',
  "Yopilishi rejalangan oylar:": 'Planned months to close:',
  "Qarzdan yopiladigan oylar:": 'Debt months that will be closed:',
  "Oylar kesimida summa:": 'Amount by month:',
  "Qoladigan qarz:": 'Remaining debt:',
  "To'lov turi": 'Payment type',
  "Yuboriladigan summa": 'Submitted amount',
  "Kutilgan summa": 'Expected amount',
  Davr: 'Period',
  "Yopiladigan oylar soni": 'Number of months to close',
  "Qarz oylar": 'Debt months',
  "Jami qarz": 'Total debt',
  "Qarzni yopish": 'Close debt',
  "1 oy to'lash": 'Pay 1 month',
  Qarzdor: 'Debtor',
  "To'lagan": 'Paid',
  'Sana': 'Date',
  'Sinf': 'Class',
  "O'qituvchi": 'Teacher',
  'Holatlar': 'Statuses',
  'Jami': 'Total',
  'Nomi': 'Name',
  'Turi': 'Type',
  'Hajmi': 'Size',
  'Manzil': 'Address',
  "Tug`ilgan sana": 'Birth date',
  "Ota-ona telefoni": 'Parent phone',
  "Profil yaratilgan sana": 'Profile created at',
  "Jami hujjatlar": 'Total documents',
  "Yangi sarlavha": 'New title',
  "Bu sinfda hozircha student yo'q.": 'No students in this classroom yet.',
  "Sinflar mavjud emas": 'No classrooms available',
  "Fanlar mavjud emas": 'No subjects available',
  "Yangi fan nomi": 'New subject name',
  "Masalan: 6-A": 'Example: 6-A',
  "Masalan: 2025-2026": 'Example: 2025-2026',
  "Ism, familiya, username yoki telefon": 'Name, surname, username or phone',
  "Ism, username yoki ota-ona telefoni...": 'Name, username or parent phone...',
  "Barcha holatlar": 'All statuses',
  "Kunlik": 'Daily',
  "Haftalik": 'Weekly',
  "Oylik": 'Monthly',
  "Choraklik": 'Quarterly',
  "Yillik": 'Yearly',
  "Hamma": 'All',
  "Hammasi": 'All',
};

const REPLACEMENTS = [
  [/\bYanvar\b/g, 'January'],
  [/\bFevral\b/g, 'February'],
  [/\bMart\b/g, 'March'],
  [/\bAprel\b/g, 'April'],
  [/\bMay\b/g, 'May'],
  [/\bIyun\b/g, 'June'],
  [/\bIyul\b/g, 'July'],
  [/\bAvgust\b/g, 'August'],
  [/\bSentabr\b/g, 'September'],
  [/\bOktabr\b/g, 'October'],
  [/\bNoyabr\b/g, 'November'],
  [/\bDekabr\b/g, 'December'],
  [/\bDUSHANBA\b/g, 'Monday'],
  [/\bSESHANBA\b/g, 'Tuesday'],
  [/\bCHORSHANBA\b/g, 'Wednesday'],
  [/\bPAYSHANBA\b/g, 'Thursday'],
  [/\bJUMA\b/g, 'Friday'],
  [/\bSHANBA\b/g, 'Saturday'],
  [/\bDushanba\b/g, 'Monday'],
  [/\bSeshanba\b/g, 'Tuesday'],
  [/\bChorshanba\b/g, 'Wednesday'],
  [/\bPayshanba\b/g, 'Thursday'],
  [/\bJuma\b/g, 'Friday'],
  [/\bShanba\b/g, 'Saturday'],
  [/(\d+)\s*ta\s*\/\s*sahifa/gi, '$1 per page'],
  [/Sahifa:\s*(\d+)\s*\/\s*(\d+)/gi, 'Page: $1 / $2'],
  [/Jami:\s*(\d+)/gi, 'Total: $1'],
  [/(\d+)\s*ta\s*o'quvchi/gi, '$1 students'],
  [/\bO'qituvchi\b/gi, 'Teacher'],
  [/\bO'quvchi\b/gi, 'Student'],
  [/\bSinf\b/gi, 'Class'],
  [/\bFan\b/gi, 'Subject'],
  [/\bHolat\b/gi, 'Status'],
  [/\bIzoh\b/gi, 'Note'],
  [/\bDavomat\b/gi, 'Attendance'],
  [/\bJadval\b/gi, 'Schedule'],
  [/\bQarz\b/gi, 'Debt'],
  [/\bQarzdorlar\b/gi, 'Debtors'],
  [/\bQarzdor\b/gi, 'Debtor'],
  [/\bYillik\b/gi, 'Yearly'],
  [/\bOylik\b/gi, 'Monthly'],
  [/\bHaftalik\b/gi, 'Weekly'],
  [/\bKunlik\b/gi, 'Daily'],
  [/\bChoraklik\b/gi, 'Quarterly'],
  [/\bYangi\b/gi, 'New'],
  [/\bTuri\b/gi, 'Type'],
  [/so'm/gi, 'UZS'],
];

export function autoTranslateUzToEn(value) {
  if (typeof value !== 'string') return value;
  const raw = value.trim();
  if (!raw) return value;

  const exact = EXACT_EN_MAP[raw];
  if (exact) return value.replace(raw, exact);

  let result = value;
  for (const [pattern, replacement] of REPLACEMENTS) {
    result = result.replace(pattern, replacement);
  }

  return result;
}
