export function buildAdminClassroomsWorkspaceModel(pageState) {
  return {
    t: pageState.t,
    classrooms: pageState.classrooms,
    meta: pageState.meta,
    classroomsState: pageState.classroomsState,
    createForm: {
      name: pageState.name,
      academicYear: pageState.academicYear,
      academicYearOptions: pageState.academicYearOptions,
      loading: pageState.createLoading || pageState.annualActionLoading,
      onNameChange: pageState.onNameChange,
      onNameBlur: pageState.onNameBlur,
      onAcademicYearChange: pageState.onAcademicYearChange,
      onSelectNextAcademicYear: pageState.onSelectNextAcademicYear,
      onSubmit: pageState.onCreateClassroom,
    },
    studentsModal: {
      classroom: pageState.selectedClassroom,
      open: Boolean(pageState.selectedClassroom),
      searchValue: pageState.studentSearchInput,
      studentsState: pageState.studentsState,
      removeLoading: pageState.removeLoading,
      onClose: pageState.onCloseStudentModal,
      onSearchChange: pageState.onStudentSearchChange,
      onSearchSubmit: pageState.onStudentSearchSubmit,
      onPageChange: pageState.onStudentPageChange,
      onOpenStudentDetail: pageState.onOpenStudentDetail,
      onRequestRemoveStudent: pageState.onRequestRemoveStudent,
    },
    annualModal: {
      open: pageState.annualModalOpen,
      previewState: pageState.annualPreviewState,
      actionLoading: pageState.annualActionLoading,
      onClose: pageState.onCloseAnnualModal,
      onRefresh: pageState.onRefreshAnnualPreview,
      onRequestRun: pageState.onRequestRunAnnualPromotion,
    },
    confirmModal: {
      open: pageState.confirmState.open,
      title: pageState.confirmConfig.title,
      message: pageState.confirmConfig.message,
      loading: pageState.removeLoading || pageState.annualActionLoading,
      onCancel: pageState.onCancelConfirm,
      onConfirm: pageState.onConfirm,
    },
    onOpenAnnualModal: pageState.onOpenAnnualModal,
    onOpenClassroom: pageState.onOpenStudentModal,
  };
}
